# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: nmenag
email: nmena.garzon@gmail.com
skype: nmenag
location: Bogotá, Colombia
description: Acerca de mi - Desarrollador de Software y Aplicaciones Web, amante al software libre
author: Nicolas Mena Garzón

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
sass:
  sass_dir: /assets/css/sass
  style: compressed

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/nmenag
  - title: github
    url: https://github.com/nmenag
  - title: linkedin
    url: https://www.linkedin.com/pub/nicol%C3%A1s-mena-garz%C3%B3n/67/b88/579
  - title: google plus
    url: https://plus.google.com/+NicolasMenaGarz%C3%B3n12/posts
