- title: En el Desarrollo movil
  description: |
    <p class="lead">Desarrollo aplicaciones móviles hibridas usando  la plataforma<a href="http://phonegap.com/install/" target="_blank"> Phonegap/Cordova</a></p>

  logo: |
    <i class="icon-mobile-device" style="font-size:100px"></i>

- title: En el frontend
  description: |
    <p class="lead">Construyo applicaciones y sitios web  aplicando diversas tecnologías como <a href="https://angularjs.org/" target="_blank">AngularJS</a>, <a href="http://emberjs.com/" target="_blank">Ember.js</a>, <a href="http://getbootstrap.com/2.3.2/" target="_blank">Twitter Bootstrap</a>,
      <a href="http://foundation.zurb.com/" target="_blank">Foundation Zurb</a>,
      <a href="https://jquery.com/" target="_blank">jQuery</a>,
      <a href="http://lesscss.org/" target="_blank">LESS</a> y
      <a href="http://sass-lang.com/" target="_blank">SASS</a>.
    </p>
  logo: |
    <i class="icon-html" style="font-size:100px"></i>
    <i class="icon-javascript" style="font-size:100px"></i>
    <i class="icon-css" style="font-size:100px"></i>

- title: En el Backend
  description: |
    <p class="lead">Experiencia trabajando con <a href="https://www.ruby-lang.org/es/" target="_blank">Ruby</a> y <a href="http://php.net/" target="_blank">PHP</a>,  en conjunto he trabajado con motores de base de datos como <a href="http://www.postgresql.org.es/" target="_blank">PostgreSQL</a> y <a href="https://www.mysql.com/" target="_blank">MySQL</a></p>
  logo: |
    <div align="center">
      <div class="row">
        <i class="icon-ruby-on-rails" style="font-size:100px" title="Ruby"></i>
        <i class="icon-ruby" style="font-size:100px" title="Rails"></i>
        <i class="icon-php" style="font-size:100px" title="PHP"></i>
      </div>
      <i class="fa fa-plus" style="font-size:100px"></i>
      <div class="row">
        <i class="icon-postgres" style="font-size:100px" title="PostgreSQL"></i>
        <i class="icon-mysql" style="font-size:100px" title="MySQL"></i>
      </div>
    </div>